### ISSUE TITLE
Add support for disabling formatter on specific lines, please

### ISSUE THREAD

**Issue by anion155** [mohd-akram/html-format#5]
aka
```
<div>
  <!-- html-format disable -->
  <script>very-ling-minified-js-for-example</script>
  <!-- html-format enable -->
</div>
```

**Comment by mohd-akram** [comment]
I don't believe we format script tags in the first place. What behavior do you get?

**Comment by anion155** [comment]
Well currently it's about minified scripts like TiktokAnalyticsObject snippet gets formatted after saving. I will look if I can disable it by js formatters. But it would be nice to have same functionality for html tags

**Comment by mohd-akram** [comment]
Are you using html-format through the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=mohd-akram.vscode-html-format)? My extension does not format JS, you might have VS Code's HTML formatting turned on instead. You can specify the formatter via `settings.json`:

```json
"[html]": {
  "editor.defaultFormatter": "mohd-akram.vscode-html-format"
}
```

The default one is called `vscode.html-language-features`. The docs for it are [here](https://code.visualstudio.com/docs/languages/html#_formatting).
