### ISSUE TITLE
Safari: SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by wscourge** [mohd-akram/html-format#7]
I get the following error trying to use this client-side in Safari:

>  SyntaxError: Invalid reqular expression: invalid group specifier name

**Comment by mohd-akram** [comment]
Which version of Safari? Please provide the full stack trace or the line number where this happens.

**Comment by wscourge** [comment]
The easiest way to reproduce will be using [Tauri v1](https://tauri.app/), it happens there. Sorry for not being more precise: it is not Safari, but MacOS WebKit: see [more info here](https://tauri.app/v1/references/webview-versions/#webkit-macos-ios--linux). 

My Mac:

![image](https://github.com/mohd-akram/html-format/assets/16985871/6e2ac916-3b5c-402f-a028-2db4b1a88849)

My Safari:
![image](https://github.com/mohd-akram/html-format/assets/16985871/59dcab10-9e14-4835-9b1d-d61e65195cf2)

**Comment by mohd-akram** [comment]
Your version of Safari is a bit old. The regular expressions use negative lookbehind, which according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion#browser_compatibility) is supported starting from 16.4. Are you able to upgrade your WebKit version?

**Comment by wscourge** [comment]
I am, not sure that my app's users are tho.

**Comment by mohd-akram** [comment]
I see. Safari 16.4 is available for macOS [starting from Big Sur](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes), so hopefully that's most of your users. In the meantime, I'll see if I can make the formatting work without it.

**Comment by mohd-akram** [comment]
This turned out to be easier than I thought. Fixed in ba1bc6fe94719c32fe4dfadf27b6c3393e3f6cf5 and released in 1.1.7.

**Comment by wscourge** [comment]
Thank you!
